### ISSUE TITLE
re-enable authentication

### ISSUE THREAD

**Issue by meeDamian** [lncm/invoicer#11]
All API calls should be behind basic auth.

All non-API calls - ??

Should I expose some more static files other than `index.html` - ex. `favicon.ico` the apple icons for the iPad logo, etc? cc. @AnotherDroog

**Comment by AnotherDroog** [comment]
Yes, a static folder for more exposing more files on http would be great!

**Comment by meeDamian** [comment]
ok.

**Comment by meeDamian** [comment]
Done in v0.0.12
