### ISSUE TITLE
Past transactions endpoint

### ISSUE THREAD

**Issue by meeDamian** [lncm/invoicer#12]
Create endpoint for past received LN payments. 

Should I also have one for received Bitcoin payments? (that adds a little bit of complexity…)

That endpoint should only be accessible if authentication from #11 is turned on.

**Comment by AnotherDroog** [comment]
I think it would be very nice to show on-chain also but no problem to defer it to later

**Comment by meeDamian** [comment]
Also, sorry @BTCln, but I need to abstract away the output here, as I want to define an interface that will work with any LN node in the background.
