### ISSUE TITLE
invoicer should automatically reconnect if lnd gets restarted

### ISSUE THREAD

**Issue by nolim1t** [lncm/invoicer#17]
Currently invoicer generates errors after LND is restarted. invoicer should automatically reconnect if lnd gets restarted, or at least establish a new connection (and clean up that connection) to query LND.

## To Reproduce

* Start LND
* Start invoicer
* Query invoicer (i.e. connstrings endpoint)
* Stop LND
* Try to query Invoicer and you get an error rather than the connection strings

**Comment by nolim1t** [comment]
```
{"error":"Can't get info from LN node: rpc error: code = Unimplemented desc = unknown service lnrpc.Lightning"}
```

**Comment by meeDamian** [comment]
According to Golang's GRPC library documentation, retrying is disabled by default. However it can be re-enabled by using:

```
GRPC_GO_RETRY=on

# ex:
GRPC_GO_RETRY=on go run main.go
```

Sources:
* https://godoc.org/google.golang.org/grpc
* https://github.com/grpc/grpc-go/blob/master/internal/envconfig/envconfig.go#L50-L51

**Comment by nolim1t** [comment]
didn't seem to work as commented in #10 but I set it as an environment variable for the container.

Should ```GRPC_GO_RETRY=on``` be prefixed in the command?

**Comment by nolim1t** [comment]
No problems. Theres a few workarounds we can do, but need an endpoint for doing a health check

**Comment by nolim1t** [comment]
reconnection is working, but just not as elegant. But ill close the issue. It's good enough for now
