### ISSUE TITLE
Add `/api/:routes`, remove `/static` 

### ISSUE THREAD

**Issue by meeDamian** [lncm/invoicer#22]

**Comment by hitchcott** [comment]
Better to have `/api/` serve the api routes and `/` serve the static routes.

Related:  https://github.com/lncm/invoicer-ui/issues/11

**Comment by meeDamian** [comment]
`gin`, the library I use doesn't seem to support that easily. Would rather not waste time on that, and move on to payment status endpoint. 

If someone's interested in playing with it in the meantime, see here: https://github.com/lncm/invoicer/tree/swap-api-with-static-routes

Goals:

* API requests served as `/api`
* everything else served at `/` if path to static dir passed as `-static-dir=`.
