### ISSUE TITLE
get rid of healthcheck

### ISSUE THREAD

**Issue by meeDamian** [lncm/invoicer#34]

**Comment by nolim1t** [comment]
A way we can fix this is having invoicer exit if it cannot find an LND instance and in future c-lightning (theres no reason to have it not run anyway). 

Docker compose already handles this and will attempt to restart invoicer if it stops. And by then it should already connect to a lnd.

The other scenario is if lnd restarts, invoicer should stop and docker-compose should restart lnd.

Or can just restart the grpc connection

**Comment by meeDamian** [comment]
Healthcheck is kill together with v0.2+
