### ISSUE TITLE
Add on-chain invoicing

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/invoicer#4]
Generate invoices for lightning wallet but on-chain.

Track payment status, ideally using bitcoind full-node, alternatively using online block-explorer.

**Comment by meeDamian** [comment]
So… monitoring using bitcoind _is [technically possible]_. Although… damn…

[technically possible]: https://bitcoin.stackexchange.com/a/50324/9223

**Comment by AnotherDroog** [comment]
That looks involved, would it be sufficient to monitor ZMQ `rawtx` for P2PKH or do we also have to parse scripts for P2PK and P2WPKH and even execute P2SH conditionals?

How do block explorers build the index that allows them to lookup by address? There must be an opportunity for reuse here

**Comment by meeDamian** [comment]
They literally build their own index in an external db.

**Comment by AnotherDroog** [comment]
I'd like to avoid running another database and a process to watch ZMQ.

How about this alternative?

bitcoind has support for watch-only addresses since this [PR](https://github.com/bitcoin/bitcoin/pull/4045)

Idea is as follows:

- enable bitcoind wallet feature
- do **not** generate privkeys in bitcoind wallet
- let lightning wallet generate on-chain payment request
- add the pubkey to watch-only addresses in bitcoind
- poll wallet RPC by known address

**Comment by meeDamian** [comment]
I am not sure if you get granular access there, or you just have a watch only wallet with a balance - probably needs investigating.

**Comment by meeDamian** [comment]
As discussed in person with @AnotherDroog, the sequence of:

1. generate new address from `lightning-cli`
	```shell
	ADDR="$(lightning-cli newaddr bech32 | jq -r '.address')"
	```

	> **NOTE:** `lnd` can be used instead
	> **NOTE_2:** `bech32` address might not be the best choice _yet_

2. Add address generated above to be watched by bitcoind

	```shell
	bitcoin-cli importaddress "${ADDR}" "payment ID or label" false
	```
	> **NOTE:** we do not need to rescan as the address is guaranteed to be freshly generated


3. Run this in a loop/periodically (until it expires)

	```shell
	bitcoin-cli listreceivedbyaddress 0 true true '"'${ADDR}'"' | jq '.[]'
	``` 
	> **NOTE:** `${ADDR}` needs to be passed in this weird way for now, because: https://github.com/bitcoin/bitcoin/issues/14173
	
should do the trick for us :)

**Comment by AnotherDroog** [comment]
Nice work detailing the steps necessary!

Does this imply we need to run a backend with cli access or can all these calls be done over REST/RPC?

**Comment by meeDamian** [comment]
Good question, I'll look into that

**Comment by meeDamian** [comment]
@BTCln how about changing the API of the invoicer a bit:

* `POST /payment` - returns both LN invoice and Bitcoin address (uses preimage hash as `:hash`)
* `POST /payment/ln` - returns only LN invoice (uses preimage hash as `:hash`)
* `POST /payment/btc` - returns only BTC address (uses randomly generated hash as `:hash`)
* `GET /payment/:hash` - returns status of the payment:
	* `paid` - LN invoice has been paid
	* `expired` - payment expired (edge case here)
	* `unconfirmed` - unconfirmed BTC payment spotted
	* `confirmed` - already confirmed BTC payment spotted (I can add number of confirmations after a space or sth)
	* `err: …` - an error occured
* `GET /info` - returns nodes info (connstrings and potentially more later)

**Comment by meeDamian** [comment]
Started with https://github.com/btcsuite/btcd/tree/master/rpcclient/examples/bitcoincorehttp, but it has many annoying limitations and is borked in odd ways. 

Looked into https://github.com/bitcoin/bitcoin/blob/master/doc/REST-interface.md, but it has no methods that we need.

Looking into RPC calls now, but ideally in a way that doesn't involve going through the CLI…

**Comment by meeDamian** [comment]
Now together with ff9df30b0ba450d9fed021593244401b5b2828fe I deem this issue closed. For bugs and changes please open separate issues.
