### ISSUE TITLE
Lightning only mode?

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/invoicer#42]
Is running without bitcoind possible?

**Comment by nolim1t** [comment]
Agree as it makes sense for neutrino

**Comment by meeDamian** [comment]
Done in https://github.com/lncm/invoicer/commit/ca7f3092dc440eb81e84bc617094efb6ac3f103e avail in 0.5.1 onwards.

**Comment by meeDamian** [comment]
See: https://github.com/lncm/invoicer/releases/tag/0.5.1
