### ISSUE TITLE
Create self-contained index.htm for public donations

### ISSUE THREAD

**Issue by meeDamian** [lncm/invoicer#5]
Change [this file] to:
1. call `GET /invoice` upon website load
	1. extract & remember `.hash` from JSON returned above
	1. extract `.invoice` from the JSON above, then prepend it with `lightning:`, and finally render and display QR code for it
1. call `GET /status/<hash>` and wait for invoice status change (`<hash> == .hash`)
1. upon successful payment or payment expiry, hide the QR and display info message 
1. add a button to generate a new invoice

LMK if you have any further questions.

[this file]: https://github.com/lncm/invoicer/blob/master/common/index.html

**Comment by hitchcott** [comment]
https://github.com/lncm/invoicer-ui

Just needs to be hooked up to real endpoints, but good to go otherwise...

**Comment by meeDamian** [comment]
Temporarily exposed and available @ : 

* `http://meedamian.ddns.net:2048/` 
* `http://meedamian.ddns.net:2048/invoice`
* `http://meedamian.ddns.net:2048/status/<hash>`

**Comment by meeDamian** [comment]
Done & temporarily deployed to http://meedamian.ddns.net:2048 . Final deployment will be posted to [lncm.io](lncm.io)
